version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    restart: unless-stopped

  # Прокси для логов getgems-parser
  log-getgems:
    image: alpine
    container_name: parser-getgems # Так он будет называться в Dozzle
    volumes:
      - ./logs/getgems-parser.log:/var/log/app.log
    command: tail -f /var/log/app.log

  # Прокси для логов gift-discovery
  log-discovery:
    image: alpine
    container_name: discovery-service
    volumes:
      - ./logs/gift-discovery.log:/var/log/app.log
    command: tail -f /var/log/app.log

  # Прокси для логов portals-parser
  log-portals:
    image: alpine
    container_name: parser-portals
    volumes:
      - ./logs/portals-parser.log:/var/log/app.log
    command: tail -f /var/log/app.log