version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    restart: unless-stopped

  log-getgems:
    image: alpine
    container_name: parser-getgems
    volumes:
      - ./logs:/var/log/my-app-logs
    command: tail -f /var/log/my-app-logs/getgems-parser.log

  core-processor:
    image: alpine
    container_name: core-processor
    volumes:
      - ./logs:/var/log/my-app-logs
    command: tail -f /var/log/my-app-logs/core-processor.log

  log-discovery:
    image: alpine
    container_name: discovery-service
    volumes:
      - ./logs:/var/log/my-app-logs
    command: tail -f /var/log/my-app-logs/gift-discovery.log

  log-portals:
    image: alpine
    container_name: parser-portals
    volumes:
      - ./logs:/var/log/my-app-logs
    command: tail -f /var/log/my-app-logs/portals-parser.log

  onchain-indexer:
    image: alpine
    container_name: onchain-indexer
    volumes:
      - ./logs:/var/log/my-app-logs
    command: tail -f /var/log/my-app-logs/onchain-indexer.log