version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    restart: unless-stopped

  # Контейнер-прокси для лога GetGems
  log-getgems:
    image: alpine
    container_name: parser-getgems
    volumes:
      - ./logs:/var/log/my-app-logs # Монтируем папку logs целиком
    command: tail -f /var/log/my-app-logs/getgems-parser.log

  # Контейнер-прокси для лога Discovery
  log-discovery:
    image: alpine
    container_name: discovery-service
    volumes:
      - ./logs:/var/log/my-app-logs # Монтируем папку logs целиком
    command: tail -f /var/log/my-app-logs/gift-discovery.log

  # Контейнер-прокси для лога Portals
  log-portals:
    image: alpine
    container_name: parser-portals
    volumes:
      - ./logs:/var/log/my-app-logs # Монтируем папку logs целиком
    command: tail -f /var/log/my-app-logs/portals-parser.log