spring:
  application:
    name: gift-discovery
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

server:
  port: 7781
  error:
    include-stacktrace: newer

logging:
  level:
    com.ceawse.giftdiscovery: INFO`
    org.springframework.web: INFO
    org.apache.coyote: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic