server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: blink-project
          __path__: /var/log/my-app-logs/*.log

    pipeline_stages:
      - regex:
          source: filename
          expression: "/var/log/my-app-logs/(?P<service_name>.*)\\.log"
      - labels:
          service_name: