spring:
  application:
    name: core
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

server:
  port: 7780
  error:
    include-stacktrace: always

logging:
  level:
    com.ceawse.blinkgift: INFO
    org.springframework.web: INFO
    org.apache.coyote: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic